version: '2.2'
services:
  broker:
    image: rabbitmq:3.7.8-management-alpine
    build: .
    healthcheck:
      test: ["CMD", "nc -z localhost 5672"]
    ports:
      - "5672:5672"
      - "15672:15672"
